# Generated by Django 5.1.4 on 2025-03-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizHub', '0002_remove_question_answers_multiplechoiceanswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('P', 'Published'), ('D', 'Draft'), ('A', 'Archived'), ('S', 'Scheduled')], default='Draft', max_length=5),
        ),
    ]
