# Generated by Django 5.1.4 on 2025-01-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('computer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('mac_adr', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('A', 'Available'), ('O', 'Occupied'), ('M', 'Maintenance')], default='A', max_length=15)),
                ('preferred_ip', models.CharField(max_length=255)),
            ],
        ),
    ]
