# Generated by Django 5.1.4 on 2025-01-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='computer',
            table='computer',
        ),
    ]
