# Generated by Django 5.1.4 on 2025-01-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer_management', '0002_alter_computer_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='preferred_ip',
        ),
    ]
