# Generated by Django 5.1.4 on 2025-01-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_management', '0003_remove_computer_preferred_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='mac_adr',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('O', 'Occupied'), ('M', 'Maintenance')], default='Available', max_length=15),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='Inactive', max_length=15)),
                ('assigned_computers', models.ManyToManyField(to='computer_management.computer')),
            ],
        ),
    ]
