# Generated by Django 5.1.4 on 2025-01-12 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_management', '0004_alter_computer_mac_adr_alter_computer_status_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='assigned_computers',
        ),
        migrations.AddField(
            model_name='student',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='computer_management.computer'),
        ),
    ]
