# Generated by Django 5.1.4 on 2025-01-13 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_management', '0006_computer_student_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='computer_management.computer', to_field='name'),
        ),
    ]
