# Generated by Django 5.1.4 on 2025-01-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer_management', '0010_alter_student_options_computer_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
