# Generated by Django 5.1.4 on 2025-01-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_management', '0012_student_curr_hist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='computer_position',
            field=models.JSONField(null=True),
        ),
    ]
