# Generated by Django 5.1.4 on 2025-01-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_management', '0013_computer_computer_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number_of_uses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
