# Generated by Django 5.1.4 on 2025-02-08 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_management', '0017_alter_student_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], max_length=20)),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='computer_management.computer', to_field='name')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='computer_management.student', to_field='code')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
